apiVersion: v1
kind: Service
metadata:
  name: public-server
spec:
  selector:
    app: public-server
  ports:
    - name: grpc-pubic-server
      protocol: TCP
      port: 9803
      targetPort: 9501
  type: NodePort